/* Generated by GoScript <github.com/kless/GoScript> */



var rating = g.Map(0, {"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2});

function nilValue() {
	var n;


	var msg = "declaration";
	if (n === undefined) {
		document.write("[OK] " + msg + "<br>");
	} else {
		document.write("[Error] " + msg + "<br>");
	}


	n = g.Map(0, {});


	msg = "using make";
	if (n !== undefined) {
		document.write("[OK] " + msg + "<br>");
	} else {
		document.write("[Error] " + msg + "<br>");
	}

}

function declare_1() {


	var numbers;
	numbers = g.Map(0, {});

	numbers.f["one"] = 1;
	numbers.f["ten"] = 10;
	numbers.f["trois"] = 3;


	if (numbers.get("trois")[0] === 3) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] Trois is the french word for the number: " + numbers.get("trois")[0] + "<br>");
	}

}

function declare_2() {

	var rating2 = g.Map(0, {"C": 5, "Go": 4.5, "Python": 4.5, "C++": 2});


	var rating = g.Map(0, {});
	rating.f["C"] = 5;
	rating.f["Go"] = 4.5;
	rating.f["Python"] = 4.5;
	rating.f["C++"] = 2;


	var code = "";
	if (JSON.stringify(rating.get("Go")[0]) === JSON.stringify(rating2.get("Go")[0])) {
		document.write("[OK] comparing same value<br>");
	} else {
		document.write("[Error] rating[\"Go\"]: " + rating.get("Go")[0] + "\trating2[\"Go\"]: " + rating2.get("Go")[0] + "<br>");

	}


	rating.f["Go"] = 4.7;

	if (JSON.stringify(rating.get("Go")[0]) !== JSON.stringify(rating2.get("Go")[0])) {
		code = "OK";
	} else {
		code = "Error";
	}
	document.write("[" + code + "] comparing different value<br>");

}

function reference() {

	var m = g.Map("", {});
	m.f["Hello"] = "Bonjour";

	var m1 = m;
	m1.f["Hello"] = "Salut";


	if (JSON.stringify(m.get("Hello")[0]) === JSON.stringify(m1.get("Hello")[0])) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] value in key: " + m.get("Hello")[0] + "<br>");
	}

}

function checkKey() {
	var csharp_rating = rating.get("C#")[0];

	if (csharp_rating === 0.00) {
		document.write("[OK] single key<br>");
	} else {
		document.write("[Error] value in key: " + csharp_rating + "<br>");
	}


	var multMap = g.Map("", {1: {1: "one"}, 2: {2: "two"}});
	var k_multMap = multMap.get(1, 2)[0];

	if (k_multMap === "") {
		document.write("[OK] multi-dimensional key<br>");
	} else {
		document.write("[Error] value in multi-dimensional key: " + k_multMap + "<br>");
	}


	var _ = rating.get("C#"), csharp_rating2 = _[0], ok = _[1];

	if (ok) {
		document.write("[Error] using comma<br>");
	} else {
		document.write("[OK] using comma<br>");
	}
	if (csharp_rating2 === 0.00) {
		document.write("[OK] value (using comma)<br>");
	} else {
		document.write("[Error] value in key (using comma): " + csharp_rating2 + "<br>");
	}

}

function deleteKey() {
	delete rating.f["C++"];

	var ok = rating.get("C++")[1];

	if (ok) {
		document.write("[Error]<br>");
	} else {
		document.write("[OK]<br>");
	}

}

function testRange() {
	var hasError = false;


	var value; for (var key in rating.m) { value = rating.get(key)[0];
		switch (key) {
		case "C":
			if (value !== 5) {
			document.write("[Error] key 'C': expected '5', got " + value + "<br>");
			hasError = true;
		} break;
		case "Go":
			if (value !== 4.5) {
			document.write("[Error] key 'Go': expected '4.5', got " + value + "<br>");
			hasError = true;
		} break;
		case "Python":
			if (value !== 4.5) {
			document.write("[Error] key 'Python': expected '4.5', got " + value + "<br>");
			hasError = true;
		} break;
		default:
			document.write("[Error] key not expected: " + key + "<br>");
			hasError = true;
		}
	}
	if (!hasError) {
		document.write("[OK]<br>");
	}


	for (var key in rating.m) {
		if (key !== "C" && key !== "Go" && key !== "Python") {
			document.write("[Error] key not expected: " + key + "<br>");
			hasError = true;
		}
	}
	if (!hasError) {
		document.write("[OK] omitting value<br>");
	}
}

function blankIdentifierInRange() {
	var hasError = false;


	var Max = function(slice) {
		var max = slice[0];
		var value; for (var _ in slice) { value = slice[_];
			if (value > max) {
				max = value;
			}
		}
		return max;
	};


	var A1 = g.MkArray([10], 0, [1, 2, 3, 4, 5, 6, 7, 8, 9]);
	var A2 = g.MkArray([4], 0, [1, 2, 3, 4]);
	var A3 = g.MkArray([1], 0, [1]);


	var slice = g.NilSlice();

	slice.set(A1, 0);
	if (Max(slice.f) !== 9) {
		document.write("[Error] 'A1': value expected '9', got " + Max(slice.f) + "<br>");
		hasError = true;
	}
	slice.set(A2, 0);
	if (Max(slice.f) !== 4) {
		document.write("[Error] 'A2': value expected '4', got " + Max(slice.f) + "<br>");
		hasError = true;
	}
	slice.set(A3, 0);
	if (Max(slice.f) !== 1) {
		document.write("[Error] 'A3': value expected '1', got " + Max(slice.f) + "<br>");
		hasError = true;
	}

	if (!hasError) {
		document.write("[OK]<br>");
	}
}

function main() {
	document.write("<br>== nilValue<br>");
	nilValue();
	document.write("<br>== declare_1<br>");
	declare_1();
	document.write("<br>== declare_2<br>");
	declare_2();
	document.write("<br>== reference<br>");
	reference();
	document.write("<br>== checkKey<br>");
	checkKey();
	document.write("<br>== deleteKey<br>");
	deleteKey();
	document.write("<br>== testRange<br>");
	testRange();
	document.write("<br>== blankIdentifierInRange<br>");
	blankIdentifierInRange();
} main();
