/* Generated by GoScript (github.com/kless/goscript) */









var x = 14, y = 9;


var and = x & y;
var or = x | y;
var xor = x ^ y;
var not = !true;

var lShift = 9 << 2;
var rShift = 9 >> 2;
var lShiftNeg = -9 << 2;
var rShiftNeg = -9 >> 2;
