/* Generated by GoScript (github.com/kless/goscript) */




var i = {p:undefined};
var hello = {p:undefined};
var p = {p:undefined};

(function() {
	p = i;
	var helloPtr = hello;
	document.write("helloPtr: " + helloPtr + "<br>");
}());

function nilValue() {
	var num = {p:10};
	var p = {p:undefined};


	var msg = "declaration";
	if (p.p === undefined) {
		document.write("[OK] " + msg + "<br>");
	} else {
		document.write("[Error] " + msg + "<br>");
	}


	p = num;

	msg = "assignment";
	if (p.p !== undefined) {
		document.write("[OK] " + msg + "<br>");
	} else {
		document.write("[Error] " + msg + "<br>");
	}

}

function declaration() {
	var i = {p:undefined};
	var hello = {p:undefined};
	var p = {p:undefined};

	p = i;
	var helloPtr = hello;
	document.write("p:  " + p + " " + "<br>helloPtr: " + helloPtr + "<br>");
}

function showAddress() {
	
	var i = {p:9};
	var hello = {p:"Hello world"};
	var pi = {p:3.14};
	var b = {p:true};


	document.write("Hexadecimal address of 'i' is: " + i + "<br>");
	document.write("Hexadecimal address of 'hello' is: " + hello + "<br>");
	document.write("Hexadecimal address of 'pi' is: " + pi + "<br>");
	document.write("Hexadecimal address of 'b' is: " + b + "<br>");
}

function access_1() {
	var hello = {p:"Hello, mina-san!"};

	var helloPtr = {p:undefined};
	helloPtr = hello;

	var i = {p:6};
	var iPtr = i;


	if (hello.p === "Hello, mina-san!" && helloPtr.p === "Hello, mina-san!") {
		document.write("[OK] string<br>");
	} else {
		document.write("[Error] The string \"hello\" is: " + hello + "<br>");
		document.write("\tThe string pointed to by \"helloPtr\" is: " + helloPtr.p + "<br>");
	}

	if (i.p === 6 && iPtr.p === 6) {
		document.write("[OK] int<br>");
	} else {
		document.write("[Error] The value of \"i\" is: " + i + "<br>");
		document.write("\tThe value pointed to by \"iPtr\" is: " + iPtr.p + "<br>");
	}
}

function access_2() {
	var x = {p:3};
	var y = x;

	y.p++;

	if (x.p === 4) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] x is: " + x + "<br>");
	}


	y.p++;

	if (x.p === 5) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] x is: " + x + "<br>");
	}
}

function allocation() {
	var sum = 0;
	var doubleSum = {p:undefined};
	for (var i = 0; i < 10; i++) {
		sum += i;
	}

	doubleSum.p = 0;
	doubleSum.p = sum * 2;


	if (sum === 45 && doubleSum.p === 90) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] The sum of numbers from 0 to 10 is: " + sum + "<br>");
		document.write("\tThe double of this sum is: " + doubleSum.p + "<br>");
	}
}

function parameterByValue() {

	var add = function(v) {
		v = v + 1;
		return v;
	};

	var x = 3;
	var x1 = add(x);


	if (x1 === 4 && x === 3) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] x+1 = " + x1 + "<br>");
		document.write("\tx = " + x + "<br>");
	}
}

function byReference_1() {
	var add = function(v) {
		v.p = v.p + 1;
		return v.p;
	};

	var x = {p:3};

	var x1 = add(x);

	if (x1 === 4 && x.p === 4) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] x+1 = " + x1 + "<br>");
		document.write("\tx = " + x + "<br>");
	}


	x1 = add(x);

	if (x1 === 5 && x.p === 5) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] x+1 = " + x1 + "<br>");
		document.write("\tx = " + x + "<br>");
	}

}

function byReference_2() {
	var add = function(v, i) { v.p += i; };

	var value = {p:6};
	var incr = 1;

	add(value, incr);

	if (value.p === 7) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] value = " + value + "<br>");
	}


	add(value, incr);

	if (value.p === 8) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] value = " + value + "<br>");
	}

}

function byReference_3() {
	var x = {p:3};
	var f = function() {
		x.p = 4;
	};
	var y = x;

	f();
	if (y.p === 4) {
		document.write("[OK]<br>");
	} else {
		document.write("[Error] y =  " + y.p + "<br>");
	}
}

function main() {
	document.write("<br>== nilValue<br>");
	nilValue();
	document.write("<br>== declaration<br>");
	declaration();
	document.write("<br>== showAddress<br>");
	showAddress();
	document.write("<br>== access_1<br>");
	access_1();
	document.write("<br>== access_2<br>");
	access_2();
	document.write("<br>== allocation<br>");
	allocation();
	document.write("<br>== parameterByValue<br>");
	parameterByValue();
	document.write("<br>== byReference_1<br>");
	byReference_1();
	document.write("<br>== byReference_2<br>");
	byReference_2();
	document.write("<br>== byReference_3<br>");
	byReference_3();
} main();
